# Generated by Django 4.2.5 on 2023-10-10 20:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_category_description_alter_product_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='заголовок')),
                ('slug', models.CharField(max_length=200, verbose_name='slug ')),
                ('description', models.TextField(blank=True, null=True, verbose_name='описание')),
                ('preview', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='превью')),
                ('created_at', models.DateField(default=datetime.date.today, verbose_name='дата создания')),
                ('views_count', models.IntegerField(default=0, verbose_name='количество просмотров')),
                ('is_viewable', models.BooleanField(default=True, verbose_name='признак публикации')),
            ],
            options={
                'verbose_name': 'блог',
                'verbose_name_plural': 'блоги',
            },
        ),
    ]
